Allow Terraform version to be passed as file

diff --git a/.github/workflows/linting-infrastructure-terraform.yml b/.github/workflows/linting-infrastructure-terraform.yml
--- a/.github/workflows/linting-infrastructure-terraform.yml
+++ b/.github/workflows/linting-infrastructure-terraform.yml
@@ -18,15 +18,35 @@ on:
         description: "Directory path to lint"
         default: "./terraform"
         required: false
-
+      terraform_version_file:
+        type: string
+        description: "File containing the terraform version to use"
+        required: false
+        default: "NOT_SET"
+  
 jobs:
   terraform_lint:
     runs-on: ubuntu-latest
     steps:
       - uses: actions/checkout@v3
+      - name: Set Terraform version
+        id: tf_version
+        run: |
+          if [ "${{ inputs.terraform_version_file }}" != "NOT_SET" ]; then
+            echo "Using terraform version from file"
+            if [ ! -f "${{ inputs.terraform_version_file }}" ]; then
+              echo "Terraform version file not found"
+              exit 1
+            fi
+            echo "TF_VERSION=$(cat ${{ inputs.terraform_version_file }})" >> $GITHUB_OUTPUT
+          else
+            echo "Using terraform version from input"
+            echo "TF_VERSION=${{ inputs.terraform_version }}" >> $GITHUB_OUTPUT
+          fi
+        shell: bash
       - uses: hashicorp/setup-terraform@v2
         with:
-          terraform_version: ${{ inputs.terraform_version }}
+          terraform_version: ${{ steps.tf_version.outputs.TF_VERSION }}
           terraform_wrapper: ${{ inputs.terraform_wrapper }}
       - name: "Run Terraform Lint"
         working-directory: ${{ inputs.directory }}
